name: Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install numpy matplotlib pytest pytest-md torchviz graphviz
        sudo apt-get update && sudo apt-get install -y graphviz
    
    - name: Run model verification
      id: model-test
      env:
        CUDA_VISIBLE_DEVICES: ""
        TORCH_DEVICE: "cpu"
      run: |
        echo "test-results=$(python tests/test_model.py)" >> $GITHUB_OUTPUT
    
    - name: Add Test Summary
      run: |
        echo "## Model Test Results" >> $GITHUB_STEP_SUMMARY
        cat test-summary.md >> $GITHUB_STEP_SUMMARY
    
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          models/
          visualizations/
          test-summary.md